"""update vehicle and add dealership tables

Revision ID: 7878ebaa47e0
Revises: 9c9904024dc9
Create Date: 2026-07-24 11:02:25.226849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7878ebaa47e0'
down_revision: Union[str, None] = '9c9904024dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('color', sa.String(length=50), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(length=30), nullable=False))
    op.add_column('vehicles', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'image_url')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'color')
    # ### end Alembic commands ###
